/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yakindu.sct.machineacafeprofessionnelle.java;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
